// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace HyDrata.GestaoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603190548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cooperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("TB_COOPERATIVAS");
                });

            modelBuilder.Entity("Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorMensalidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR_MENSALIDADE");

                    b.HasKey("Id");

                    b.ToTable("TB_PLANOS");
                });

            modelBuilder.Entity("Produtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("UQ_PRODUTOR_CPF");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_PRODUTOR_EMAIL")
                        .HasFilter("\"EMAIL\" IS NOT NULL");

                    b.ToTable("TB_PRODUTORES");
                });

            modelBuilder.Entity("ProdutorCooperativa", b =>
                {
                    b.Property<int>("ProdutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUTOR_ID");

                    b.Property<int>("CooperativaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COOPERATIVA_ID");

                    b.Property<DateTime>("DataAssociacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ASSOCIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ProdutorId", "CooperativaId");

                    b.HasIndex("CooperativaId");

                    b.ToTable("TB_PRODUTOR_COOPERATIVA");
                });

            modelBuilder.Entity("Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("AREA_HECTARES");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CIDADE");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("ESTADO");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<int>("PlanoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLANO_ID");

                    b.Property<int>("ProdutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUTOR_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.HasIndex("ProdutorId");

                    b.ToTable("TB_PROPRIEDADES");
                });

            modelBuilder.Entity("ProdutorCooperativa", b =>
                {
                    b.HasOne("Cooperativa", "Cooperativa")
                        .WithMany("ProdutorCooperativas")
                        .HasForeignKey("CooperativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PC_COOPERATIVA");

                    b.HasOne("Produtor", "Produtor")
                        .WithMany("ProdutorCooperativas")
                        .HasForeignKey("ProdutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PC_PRODUTOR");

                    b.Navigation("Cooperativa");

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("Propriedade", b =>
                {
                    b.HasOne("Plano", "Plano")
                        .WithMany("Propriedades")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PROPRIEDADE_PLANO");

                    b.HasOne("Produtor", "Produtor")
                        .WithMany("Propriedades")
                        .HasForeignKey("ProdutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PROPRIEDADE_PRODUTOR");

                    b.Navigation("Plano");

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("Cooperativa", b =>
                {
                    b.Navigation("ProdutorCooperativas");
                });

            modelBuilder.Entity("Plano", b =>
                {
                    b.Navigation("Propriedades");
                });

            modelBuilder.Entity("Produtor", b =>
                {
                    b.Navigation("ProdutorCooperativas");

                    b.Navigation("Propriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
